image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2

variables:
  EXE_RELEASE_FOLDER: 'InkCanvasForClass\bin\Debug'
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe'

stages:
  - build

build_job:
  stage: build
  only:
    - pushes
    - web
  script:
    - '& "$env:NUGET_PATH" restore'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release /p:Platform="Any CPU"'
  artifacts:
    expire_in: 8 yrs
    paths:
      - '$env:EXE_RELEASE_FOLDER\'
